### ISSUE TITLE
The single character wildcard search matches multiple characters

### ISSUE THREAD

**Issue by dreverri** [basho/riak_search#102]
## Description

The "?" wildcard should only match a single character. It currently matches many characters.
## To reproduce
- Install the Search hook

``` bash
search-cmd install wildcards
```
- Write an object

``` bash
curl -XPUT http://localhost:8098/riak/wildcards/1 -H 'content-type:text/plain' -d 'The quick brown fox jumped over the lazy dog'
```
- Search using a "?"

``` bash
search-cmd search wildcards "qui?"
```
## Expected

No results.
## Actual

The written object matches the query.

**Comment by rzezeski** [comment]
Try my fix when you get a chance, Dan.

**Comment by dreverri** [comment]
The wildcard query works with the proposed fix. +1

**Comment by rzezeski** [comment]
The fix has been merged.  I need to learn how to associate issues and PRs.
