### ISSUE TITLE
performance issues: PB client/mapred/pipe

### ISSUE THREAD

**Issue by rzezeski** [basho/riak_search#103]
As pointed out on the mailing list there are performance issues regarding the integration of the PB client/pipe/mapred/search (1).  Essentially mapred/search can take orders of magnitude longer via the PB client because of issues with pipe/search integration.  Until this is fixed there are two work arounds:
1. Use legacy mapreduce (2)
2. If writing an Erlang application you can still use pipe for mapreduce but make rpc calls to the `search:mapred` function.  This function is still hardcoded to use the legacy system and therefore won't be affected if the general mapreduce system is using pipe.

1: http://lists.basho.com/pipermail/riak-users_lists.basho.com/2012-April/008050.html

2: https://wiki.basho.com/Configuration-Files.html#mapred_system

**Comment by seancribbs** [comment]
@rzezeski We should talk about native PB endpoints for Search (and other apps).

**Comment by gburd** [comment]
This impacts a customer's use of search: zd #1189

**Comment by seancribbs** [comment]
Still valid? We now have a native PB endpoint for Search.
