### ISSUE TITLE
500 Internal error on utf8 document search & utf8 key doubly encoded.

### ISSUE THREAD

**Issue by kthakore** [basho/riak_search#132]
I have a 5 node cluster setup (based of the rebar dev). I got the source from:

 http://downloads.basho.com.s3-website-us-east-1.amazonaws.com/riak/CURRENT/riak-1.2.1.tar.gz

I enabled riak_search in all the configurations.

And then made a bucket 'test01' and enabled postcommit indexing. 

Then I created this document:

``` json
{
    "介绍" : "15岁的女孩与癌",
    "r_int"  : 15,
    "other" : "15岁的女孩与癌",
    "介绍介绍" : { "介绍": "12介绍" }
}
```

I performed this search: 

http://localhost:8091/solr/test01/select?q=r_int:15

and I get this message:

``` erlang
{error,{error,{case_clause,{{badfun,#Fun},
                            [{mi_server,iterate,6},{mi_server,lookup,8}]}},
              [{riak_search_client,search_doc,8},
               {riak_solr_searcher_wm,run_query,1},
               {riak_solr_searcher_wm,to_xml,2},
               {webmachine_resource,resource_call,3},
               {webmachine_resource,do,3},
               {webmachine_decision_core,resource_call,1},
               {webmachine_decision_core,decision,1},
               {webmachine_decision_core,handle_request,2}]}}
```

Also searching with this doesn't work:

http://localhost:8091/solr/test01/select?q=介绍:15岁的女孩与癌

but when I doubly encode the key (介绍) in utf8 it works.

**Comment by kthakore** [comment]
Btw the doubly encoded key string becomes:

http://localhost:8091/solr/test01/select?q=ä»ç»:15岁的女孩与癌

**Comment by kthakore** [comment]
Doing OR and AND operations also time out:

http://localhost:8091/solr/test01/select?q=(other:%2215%E5%B2%81%E7%9A%84%E5%A5%B3%E5%AD%A9%E4%B8%8E%E7%99%8C%22%20OR%20other:%22red%22)

``` erlang
{error,{error,{case_clause,timeout},
              [{riak_search_client,search_doc,8},
               {riak_solr_searcher_wm,run_query,1},
               {riak_solr_searcher_wm,to_xml,2},
               {webmachine_resource,resource_call,3},
               {webmachine_resource,do,3},
               {webmachine_decision_core,resource_call,1},
               {webmachine_decision_core,decision,1},
               {webmachine_decision_core,handle_request,2}]}}
```

**Comment by kthakore** [comment]
http://localhost:8091/solr/test01/select?q=(other:%2215%E5%B2%81%E7%9A%84%E5%A5%B3%E5%AD%A9%E4%B8%8E%E7%99%8C%22%20OR%20other:%22red%22)

and 

http://localhost:8091/solr/test01/select?q=r_int:15

work fine with riak 1.2.0

**Comment by jonmeredith** [comment]
We're focusing out efforts on our SOLR-based replacement, yokozuna.
