### ISSUE TITLE
Solr search with rows > 15 returns empty result

### ISSUE THREAD

**Issue by dtonys** [basho/riak_search#135]
I am searching text inside of a description field of a post object.  I have 50 objects each with the word "This" as part of the text.

When I query for the word "This" it should return the whole list of 50 post objects.  But if I try to get a list of over 15 results, I get an empty response.

If I query with rows <= 15, then my search comes back fine:

```
curl "http://10.0.1.49:8100/solr/posts/select?start=0&rows=15&q=description:This"

<?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader">
<int name="status">0</int>
<int name="QTime">7</int>
<lst name="params">
  <str name="indent">on</str>
  <str name="start">0</str>
  <str name="q">description:This</str>
  <str name="q.op">or</str>
  <str name="filter"></str>
  <str name="df">value</str>
  <str name="wt">standard</str>
  <str name="version">1.1</str>
  <str name="rows">50</str>
</lst>
</lst>
<result name="response" numFound="50" start="0" maxScore="0.353553">
<doc>
  <str name="id">1
  </str>
  <str name="category">Strategy
  </str>
  <str name="description">This is a pin 0
  </str>
  <str name="posterId">user17@gmail.com
  </str>
</doc>
<doc>
  <str name="id">10
  </str>
  <str name="category">Casino
  </str>
  <str name="description">This is a pin 9
  </str>
  <str name="posterId">user18@gmail.com
  </str>
</doc>
...More Results...
```

If I query with rows > 15, I get an empty result:

```
curl "http://10.0.1.49:8100/solr/posts/select?start=0&rows=16&q=description:This"
curl: (52) Empty reply from server
```

Also, If I query with rows > 15 when there is only 1 result, the query works fine and returns the one result.

After looking around it doesn't seem like any Riak search settings should limit the results to under 15 by default, so this seems like a bug.

**Comment by seancribbs** [comment]
@dtonys Does it still return an empty response if you use `fl=id` in the query string? It could be that the index document for a result is missing, and you only hit it when you request > 15 results.

**Comment by dtonys** [comment]
Adding 'fl=id' to the query string returns a correct list of IDs, so it must be as you suspect.

**Comment by dtonys** [comment]
Ok after further investigation is looks like there's some messed up or missing index data, as queries for some individual objects are ok while others return the same empty message when I query their description.  So the problem is with my index data, not the solr search.  My bad.  Thanks for your help.
