### ISSUE TITLE
riak_search code.

### ISSUE THREAD

**Issue by mchendil** [basho/riak_search#144]
while I trying to create first users in Riak, I am facing following as below:
## URL passing:

curl -H 'Content-Type: application/json'  -X POST http://localhost:8080/riak-cs/user   --data '{"email":"foobar@example.com", "name":"admin user"}'
## Response:

<HTML><HEAD><TITLE>404 Not Found</TITLE></HEAD><BODY><H1>Not Found</H1>The requested document was not found on this server.<P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></BODY></HTML>root@localhost:/etc/riak#

Kindly help me on this.

**Comment by rzezeski** [comment]
This looks like a RiakCS issue. Closing.
