### ISSUE TITLE
Riak Search for Java Client API

### ISSUE THREAD

**Issue by jgouda** [basho/riak_search#148]
The Riak Java Client API does not support querying of Riak Search. but currently , the Ruby, Python, PHP, and Erlang clients are supported. Do you have any road map for the Java Client to support Riak Search.

Regards,
Jagan

**Comment by broach** [comment]
The Java Client currently supports Search through Map Reduce: http://basho.github.io/riak-java-client/1.4.0/com/basho/riak/client/DefaultRiakClient.html#mapReduce(java.lang.String%2C%20java.lang.String)

In version 2.0 of the Java Client we plan to offer a direct API that does not use Map Reduce
