### ISSUE TITLE
Which version's solr(lucene) grammar is riak 2.0 search going to support?

### ISSUE THREAD

**Issue by eminarcissus** [basho/riak_search#159]
I'm planning to test out migrating riak 1.4 to riak 2.0 test version, in introduce page I saw it seems support all solr dialects, so I'm interested at which version does it supports right now, since solr 4.0 it starts to support regular expression on search(http://stackoverflow.com/questions/9332343/what-regular-expression-features-are-supported-by-solr-edismax), and I've took a glance at source code seems currently only it does compile regular expression based on wildcard, is there any possibility to enable this feature?

**Comment by seancribbs** [comment]
@eminarcissus Search in Riak 2.0 is [_actually_ Solr](/basho/yokozuna), with Riak doing the distribution. `riak_search` is being deprecated.
